spring.application.name=demo

spring.datasource.url=jdbc:mysql://${MYSQLHOST:switchback.proxy.rlwy.net}:${MYSQLPORT:34357}/${MYSQLDATABASE:railway}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:tVQNdDQuVZpHvWXKxKENtfirgZwhAhWl}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

#spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
#spring.datasource.username=postgres
#spring.datasource.password=lQQDcffdLQIhvIPgtdeGWmYkQtBdFMjI
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#server.port=8080